// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package cmd

import (
	"github.com/n-creativesystem/rbns/bus"
	"github.com/n-creativesystem/rbns/config"
	"github.com/n-creativesystem/rbns/handler/gateway"
	"github.com/n-creativesystem/rbns/handler/grpcserver"
	"github.com/n-creativesystem/rbns/handler/grpcserver/middleware"
	"github.com/n-creativesystem/rbns/handler/restserver"
	"github.com/n-creativesystem/rbns/handler/restserver/middleware/auth"
	"github.com/n-creativesystem/rbns/handler/restserver/social"
	"github.com/n-creativesystem/rbns/infra"
	"github.com/n-creativesystem/rbns/service"
	"github.com/n-creativesystem/rbns/storage"
	"github.com/spf13/pflag"
)

// Injectors from wire.go:

func initializeRun(flags *pflag.FlagSet) (*servers, error) {
	configConfig, err := config.NewFlags2Config(flags)
	if err != nil {
		return nil, err
	}
	grpcGateway, err := gateway.New(configConfig)
	if err != nil {
		return nil, err
	}
	socialService := social.ProvideService(configConfig)
	authMiddleware := auth.NewAuthMiddleware(configConfig, socialService)
	busBus := bus.GetBus()
	factorySet, err := infra.NewFactory(configConfig, busBus)
	if err != nil {
		return nil, err
	}
	v := storage.NewKeyPairs(configConfig)
	store := storage.NewSessionStore(factorySet, v)
	tenantImpl := service.NewTenantImpl()
	factory, err := storage.Initialize(factorySet)
	if err != nil {
		return nil, err
	}
	server, err := restserver.New(grpcGateway, configConfig, authMiddleware, store, socialService, tenantImpl, factory)
	if err != nil {
		return nil, err
	}
	permissionImpl := service.NewPermissionService()
	permissionServer := grpcserver.NewPermissionServer(permissionImpl)
	userImpl := service.NewUserService()
	organizationImpl := service.NewOrganizationService(userImpl)
	organizationAggregationImpl := service.NewOrganizationAggregation(permissionImpl, organizationImpl, userImpl)
	organizationServer := grpcserver.NewOrganizationService(organizationImpl, organizationAggregationImpl)
	userServer := grpcserver.NewUserServer(userImpl, organizationAggregationImpl)
	tenant := middleware.NewTenantMiddleware(configConfig)
	grpcServer := grpcserver.New(permissionServer, organizationServer, userServer, tenant)
	cmdServers := newServer(server, grpcServer, configConfig)
	return cmdServers, nil
}
