package consts

const (
	API_KEY        = "API_KEY"
	DATABASE_TYPE  = "DATABASE_TYPE"
	OMIT_HEADERS   = "OMIT_HEADERS"
	HTTP           = "HTTP"
	HTTP_PORT      = "HTTP_PORT"
	GRPC           = "GRPC"
	GRPC_PORT      = "GRPC_PORT"
	DEBUG          = "DEBUG"
	WHITELIST      = "WHITELIST"
	SECURE         = "SECURE"
	UI             = "UI"
	UI_PREFIX      = "UI_PREFIX"
	MASTER_DSN     = "MASTER_DSN"
	SLAVE_DSN      = "SLAVE_DSN"
	MAX_IDLE_CONNS = "MAX_IDLE_CONNS"
	MAX_OPEN_CONNS = "MAX_OPEN_CONNS"
	MAX_LIFE_TIME  = "MAX_LIFE_TIME"
	STATIC_ROOT    = "STATIC_ROOT"
	STATIC_INDEXES = "STATIC_INDEXES"
	BASE_URL       = "BASE_URL"
)
