name: Build and Deploy

on:
  push:
    tags: ['v[0-9]+.[0-9]+.[0-9]+']

# Workflowsで使用する環境変数を定義
env:
  REPOSITORY_NAMESPACE: ncreativesystem
  IMAGE_NAME: rbns
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  setup-build-publish:
    name: Setup, Build, Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: version
        id: version
        run: |
          echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      # Docker imageのビルド
      - name: Build with Docker
        run: |
          VERSION=${{ steps.version.outputs.VERSION }}
          IMAGE="${REPOSITORY_NAMESPACE}/${IMAGE_NAME}"
          make build/all-in-one IMAGE_NAME="${IMAGE}:${VERSION}-all-in-one"
          make build/backend IMAGE_NAME="${IMAGE}:${VERSION}-api-only"
          docker tag "${IMAGE}:${VERSION}-api-only" "${IMAGE}:latest"

      # ビルド済みのイメージをGithub PackagesへPush
      - name: Push the image to Github Packages
        run: |
          VERSION=${{ steps.version.outputs.VERSION }}
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          IMAGE="${REPOSITORY_NAMESPACE}/${IMAGE_NAME}"
          docker push "${IMAGE}:${VERSION}-all-in-one"
          docker push "${IMAGE}:${VERSION}-api-only"
          docker push "${IMAGE}:latest"
